exec:
  allow:
    - '^dart-sass-embedded$'
    - '^go$'
    - '^npx$'
    - '^postcss$'
    - '^rst2html.py$'
    - '^asciidoctor$'
  osenv:
    - "(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|RUBYLIB)$"