# Hugo Global Settings 
## Site Details
baseURL: '/'
languageCode: 'en-us'
title: 'MiloDocs'

## Misc
enableGitInfo: true 
enableEmoji: true 
enableRobotsTXT: true 

# Log Settings
ignoreLogs:
  - error-remote-getcsv